### PR TITLE
Update README.md for docker compose v2

### PR DESCRIPTION
**Pull request by jackyko1991**
upgrade for docker compose v2:
https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose

### CODE REVIEW

**Comment by pwalczysko** [comment]
Do you want to update the tests as well please ? https://github.com/ome/docker-example-omero/blob/master/test.sh

**Comment by jackyko1991** [comment]
@pwalczysko files updated accordingly

**Comment by pwalczysko** [comment]
Do you want to approve the GA workflow please @jburel @joshmoore or @sbesson ?

**Comment by joshmoore** [comment]
If the tests are passing, this makes sense to me. I've not updated the habit myself, but maybe this will help. Thanks, @jackyko1991!

**Pull request merged**
